module.exports = {
  // defaultSidebar: [{type: 'autogenerated', dirName: '.'}],
  defaultSidebar: [
    {
      type: 'doc',
      id: 'quick-start',
      label: 'Quick Start',
    },
    {
      type: 'doc',
      id: 'tutorial/chapter1-first-steps',
      label: 'Tutorial 🚀',
    },
    {
      type: 'category',
      label: 'Basics',
      collapsed: false,
      // link: {
      //   type: 'generated-index',
      //   slug: 'basics',
      // },
      items: [
        'basics/selecting-and-skipping',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Usage',
      collapsed: false,
      // link: {
      //   type: 'generated-index',
      //   slug: 'advanced-usage',
      // },
      items: [
        'advanced-usage/writing-plugins',
      ],
    },
    {
      type: 'category',
      label: 'Best Practices (soon)',
      collapsed: true,
      items: [
        'best-practices/best-practice',
      ],
    },
  ],
};
