module.exports = {
  // defaultSidebar: [{type: 'autogenerated', dirName: '.'}],
  defaultSidebar: [
    {
      type: 'doc',
      id: 'quick-start',
      label: 'Quick Start',
    },
    {
      type: 'doc',
      id: 'tutorial/part1-first-steps',
      label: 'Tutorial 🚀',
    },
    {
      type: 'category',
      label: 'Features',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: 'features',
      },
      items: [
        'features/tags',
        'features/deferred-actions',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Usage',
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: 'advanced-usage',
      },
      items: [
        'advanced-usage/writing-plugins',
      ],
    },
    {
      type: 'category',
      label: 'Best Practices (soon)',
      collapsed: true,
      items: [
        'best-practices/best-practice',
      ],
    },
  ],
};
