module.exports = {
  // defaultSidebar: [{type: 'autogenerated', dirName: '.'}],
  defaultSidebar: [
    {
      type: 'doc',
      id: 'quick-start',
      label: 'Quick Start',
    },
    {
      type: 'category',
      label: 'Tutorial 🚀',
      collapsed: false,
      items: [
        'tutorial/chapter1-first-steps',
        'tutorial/chapter2-data-models',
      ],
    },
    {
      type: 'category',
      label: 'Basics',
      collapsed: false,
      items: [
        'basics/selecting-and-skipping',
        'basics/parameterized-scenarios',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/using-plugins',
        'guides/writing-plugins',
      ],
    },
    {
      type: 'category',
      label: 'Best Practices (soon)',
      collapsed: true,
      items: [
        'best-practices/best-practice',
      ],
    },
  ],
};
